### ISSUE TITLE
Request entity too large during an attemp to verify a contract on test net

### ISSUE THREAD

**Issue by playsnook** [harmony-one/explorer-v2-frontend#115]
![image](https://user-images.githubusercontent.com/85632593/150015477-51091571-5061-4989-8155-f0eb67f08c62.png)

**Comment by victaphu** [comment]
Duplicate of https://github.com/harmony-one/contract-verification-service/issues/6

Assigning to me

**Comment by victaphu** [comment]
Hi @playsnook can you try this again?

Btw, please refer to this set of information for verifying contracts:
https://victa-kwok-wai-phu.gitbook.io/harmony-contract-verification-service/tutorials/verifying-contracts-using-hardhat-and-harmony-explorer

I made the request up to 1 MB so this should work now

**Comment by StoneHeart99** [comment]
hi @victaphu,
I have tried to verify contract by following the steps in https://github.com/victaphu/harmony-contract-verification-tutorial. I managed to verify most of the contracts, however there is one contract still cannot be verified due to the "request entity too large" error.

```
Error in plugin @nomiclabs/hardhat-etherscan: Failed to send contract verification request.
Endpoint URL: https://ctrver.t.hmny.io/verify
The HTTP server response is not ok. Status code: 413 Response text: {"status":413,"message":"request entity too large"}
``` 

Is it possible to increase the file limit or number of file for the request ?

**Comment by victaphu** [comment]
Hi @StoneHeart99 how big is the file? I think its currently set to 100kb verification

**Comment by StoneHeart99** [comment]
@victaphu the file is around 130kb.

**Comment by victaphu** [comment]
Hi all, this should be fixed in the latest release. the issue was with a form submission to the contract verifier which didn't handle the larger file-sizes.
